### ISSUE TITLE
Allow passing cast object to render function

### ISSUE THREAD

**Issue by ngocdaothanh** [marionebl/svg-term#12]
Current `render`:
https://github.com/marionebl/svg-term/blob/master/src/index.tsx

```
const {load} = require('load-asciicast');
...
export function render(raw: string, options: SvgTermOptions = {}): string
...
const cast = load(...)
```

------

My use case:

Before calling `render`,
I want to use `load` of load-asciicast first to get some information about the cast (length ect.),
after that I'll call `render` later.

With the current `render`, the raw data needs to be loaded twice (once by myself, and once by `render`).

With below additional signature, the raw data can be loaded only once:

```
export function render(cast: any, options: SvgTermOptions = {}): string
```

**Comment by marionebl** [comment]
I am on board with this - care to lend a hand?

**Comment by ngocdaothanh** [comment]
Thanks. How can I help?

**Comment by marionebl** [comment]
[load-asciicast](https://github.com/marionebl/load-asciicast/blob/master/src/loadasciicast/load.cljs) would have to be adapted to expose the functionality.

**Comment by ngocdaothanh** [comment]
I'm more familiar with load-asciicast and svg-term after working on https://github.com/marionebl/svg-term/issues/13. I'll create a PR for this issue after the PRs for #13 are merged.

**Comment by ngocdaothanh** [comment]
I've created the PR:
https://github.com/marionebl/svg-term/pull/15/files
