### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by ngocdaothanh** [marionebl/svg-term#13]
This 1.6MB cast causes out of memory:
https://asciinema.org/a/170142

Also try this 4.2MB:
https://asciinema.org/a/234628

My Nodejs process crashes after 2GB of memory is consumed.

**Comment by ngocdaothanh** [comment]
This line causes the problem:
https://github.com/marionebl/svg-term/blob/master/src/index.tsx

```
const cast = load(json, options.width, typeof options.height === 'number' ? options.height + 1 : undefined);
```

asciinema v2 supports streaming:
https://github.com/asciinema/asciinema/blob/develop/doc/asciicast-v2.md

So instead of loading all the cast to memory, `load` should be improved to give each frame one by one.

**Comment by marionebl** [comment]
Yes, streaming the frames might solve this problem. Please note that [`load-asciicast`](https://github.com/marionebl/load-asciicast) is only a small wrapper around the ClojureScript implementation of asciinema. 

I am not proficient in ClojureScript and barely made the current `load-asciicast` wrapper work - if you have experience with ClojureScript help with exposing a lazy interface into `asciinema.player.asciicast` is greatly appreciated.

**Comment by ngocdaothanh** [comment]
FYI termtosvg can output SVG files without memory problem, but they are very big:
https://github.com/nbedos/termtosvg/issues/103

**Comment by ngocdaothanh** [comment]
Memo:

As mentioned in the termtosvg issue above, to avoid big output, termtosvg supports limiting frame rate with:
`-m, --min-frame-duration=MIN_DURATION`

It also supports a related feature:
`-M, --max-frame-duration=MAX_DURATION`

These are very nice-to-have features for svg-term.

**Comment by ngocdaothanh** [comment]
There are many places in svg-term that use `cast.frames`, and it's assumed as a fully loaded array.

To avoid the memory problem, there are 2 things to improve:
* Change the code that loads the frames (load-asciicast library, and its dependency asciinema-player if necessary/possible), to support limiting frame rate, to reduce the number of elements in `cast.frames`.
* Change svg-term to support writing to disk, instead of using memory when converting to SVG. This is a nice-to-have feature, so that svg-term can be used in a web server program that supports converting many SVGs at the same time, without blowing up the server memory.

**Comment by ngocdaothanh** [comment]
> support limiting frame rate

It seems the `at-hz` function is what we want:
https://github.com/asciinema/asciinema-player/commit/30dd41444fae58b1591931314746da6f7ac2b1f0#diff-63f586c713aef6ae4d8c8912cbbb159a

**Comment by marionebl** [comment]
In my mind there are two big directions we can take to tackle this problem:

1. Enable full streaming support. I want this to be independent of IO (e.g. we do not need to write to disk in `svg-term`). Will require changes in `load-asciicast` (no idea about the specifics) and svg-term. Ideally we would expose a second method that exposes streaming to consumers. Consumers (e.g. `svg-term-cli`) then may decide to stream to disk directly. This will make the size optimizations in `svg-term` harder and less efficient.

2. Decrease the amount of data via `at-hz` (great find!). We should do some test which effects this has on the output. In theory 30hz/60hz should be enough to generate high-fidelity SVGs.

**Comment by ngocdaothanh** [comment]
I've created PR for load-asciicast to add `idle` and `fps` options:
https://github.com/marionebl/load-asciicast/pull/2/files

**Comment by ngocdaothanh** [comment]
I've also created PR for svg-term:
https://github.com/marionebl/svg-term/pull/14/files

**Comment by ngocdaothanh** [comment]
Please see the 2 PRs.

I've tried. After setting `fps`, there's no more memory problem with the casts mentioned above.

**Comment by ngocdaothanh** [comment]
Thanks for reviewing the PRs and releasing the new versions. I'll close this issue.
