### ISSUE TITLE
Allow theming the font as well

### ISSUE THREAD

**Issue by gaborcsardi** [marionebl/svg-term#6]
Unfortunately the current first default, Monaco, does not look good for ascii boxes, even if the line height is 1.0, because its box-drawing characters are not full height. So there is a gap. 

Maybe the best would be to keep the current list of default fonts, and allow prepending new ones via the theme?

**Comment by marionebl** [comment]
Great idea - do you also have suggestions for a better default?

**Comment by gaborcsardi** [comment]
I don't think the default is bad, I think it is reasonable.

**Comment by marionebl** [comment]
Do you have an example for a monospace font that does not exhibit the problematic rendering with ascii box-drawing characters?

I'd appreciate a PR to introduce this feature, want to lend a hand?

I envision making the `font-family` themeable boils down to these changes (untested):

https://github.com/marionebl/svg-term/blob/d376d203cb331e34d152aeeb064eb0a430c164bf/src/index.tsx#L21-L23

to e.g. 

```tsx
const StyledContainer = styled.g` 
   font-family: ${props => props.fontFamily}; 
`; 
```

and passing fontFamily to the `StyledContainer` callsite at

https://github.com/marionebl/svg-term/blob/d376d203cb331e34d152aeeb064eb0a430c164bf/src/index.tsx#L106

like this:

```tsx
<StyledContainer fontFamily={theme.fontFamily} fontSize={theme.fontSize}> 
```

Finally the former hardcoded font-chain would have to be added to the [default theme](https://github.com/marionebl/svg-term/blob/d376d203cb331e34d152aeeb064eb0a430c164bf/src/default-theme.js):

```js
module.exports = {
  0: [40, 45, 53], // Black
  1: [232, 131, 136], // Red
  2: [168, 204, 140], // Green
  3: [219, 171, 121], // Yellow
  4: [113, 190, 242], // Blue
  5: [210, 144, 228], // Magenta
  6: [102, 194, 205], // Cyan
  7: [185, 191, 202], // White
  8: [111, 119, 131], // Light Black
  9: [232, 131, 136], // Light Red
  10: [168, 204, 140], // Light Green
  11: [219, 171, 121], // Light Yellow
  12: [115, 190, 243], // Light Blue
  13: [210, 144, 227], // Light Magenta
  14: [102, 194, 205], // Light Cyan
  15: [255, 255, 255], // Light White
  background: [40, 45, 53], // background color
  bold: [185, 192, 203], // Default bold text color
  cursor: [111, 118, 131], // Cursor color
  text: [185, 192, 203], // Default text color,
  fontSize: 1.67,
  lineHeight: 1.3,
  fontFamily: 'Monaco, Consolas, Menlo, \'Bitstream Vera Sans Mono\', \'Powerline Symbols\', monospace'
};
```

**Comment by gaborcsardi** [comment]
> Do you have an example for a monospace font that does not exhibit the problematic rendering with ascii box-drawing characters?

Menlo and Fira Code seem fine.

Sure, I can send a PR, soonish. :)
